s0.initCam(1)

global.filePrefix = "file://s:";

// Dancing Dog
s3.initVideo("https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExazdldDR4dnVqYmxrbGJiN3F5Ym5sczRqNnFiNzFyenVyYjkzOWdyZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/vVzH2XY3Y0Ar6/giphy.mp4")

// Cute Mouse
s3.initVideo("https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYmxhNzU2MTJ1aXRxazdrNnRkdGRicmdhcjZiN2JxemIxYXRjaHRqYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/EEq4P6RNIyb04/giphy.mp4")

s3.initVideo(`${filePrefix}/VJ/akukan.mp4`)
s3.initVideo(`${filePrefix}/VJ/alien_FHD_arfa.mp4`)
s3.initVideo(`${filePrefix}/VJ/alien_FHD_SIAN.mp4`)
s3.initVideo(`${filePrefix}/VJ/blue_go_forward_cyber.mp4`)
s3.initVideo(`${filePrefix}/VJ/crossing.mp4`)
s3.initVideo(`${filePrefix}/VJ/enzi.mp4`)
s3.initVideo(`${filePrefix}/VJ/future.mp4`)
s3.initVideo(`${filePrefix}/VJ/hanshin.mp4`)
s3.initVideo(`${filePrefix}/VJ/inazuma.mp4`)
s3.initVideo(`${filePrefix}/VJ/kawara.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 01.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 02.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 03.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 04.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 05.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 06.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 07.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 08.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 09.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 10.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 11.mp4`)
s3.initVideo(`${filePrefix}/VJ/KillU 12.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol1_A.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol1_B.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol1_C.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol1_D.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol1_E.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol1_F.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol1_G.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol2_A.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol2_B.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol2_C.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol2_D.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol2_E.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol2_F.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol2_G.mp4`)
s3.initVideo(`${filePrefix}/VJ/Kryo_VJvol2_H.mp4`)
s3.initVideo(`${filePrefix}/VJ/moyumoyu.mp4`)
s3.initVideo(`${filePrefix}/VJ/mozibake.mp4`)
s3.initVideo(`${filePrefix}/VJ/oberisk.mp4`)
s3.initVideo(`${filePrefix}/VJ/piccoA_alien_FHD_PINK.mp4`)
s3.initVideo(`${filePrefix}/VJ/piccoA_arfa.mp4`)
s3.initVideo(`${filePrefix}/VJ/piccoA_FHD_neon_shakeface.mp4`)
s3.initVideo(`${filePrefix}/VJ/piccoA_FHD_neon_shakehip.mp4`)
s3.initVideo(`${filePrefix}/VJ/piccoA_FHD_PINK.mp4`)
s3.initVideo(`${filePrefix}/VJ/piccoA_FHD_PINK_arfa.mp4`)
s3.initVideo(`${filePrefix}/VJ/piccoA_neon_shakehip_V.mp4`)
s3.initVideo(`${filePrefix}/VJ/piccoA_water_V.mp4`)
s3.initVideo(`${filePrefix}/VJ/piccoB_FHD_PINK.mp4`)
s3.initVideo(`${filePrefix}/VJ/piccoB_FHD_PINK_arfa.mp4`)
s3.initVideo(`${filePrefix}/VJ/pink_purple_marble20sec.mp4`)
s3.initVideo(`${filePrefix}/VJ/pipipi_FHD_arfa.mp4`)
s3.initVideo(`${filePrefix}/VJ/pipipi_stare.mp4`)
s3.initVideo(`${filePrefix}/VJ/psyco.mp4`)
s3.initVideo(`${filePrefix}/VJ/purple_marble20sec.mp4`)
s3.initVideo(`${filePrefix}/VJ/shinjuku1.mp4`)
s3.initVideo(`${filePrefix}/VJ/shinjuku2.mp4`)
s3.initVideo(`${filePrefix}/VJ/shinjuku3.mp4`)
s3.initVideo(`${filePrefix}/VJ/Shinjuku_Night_1-1.mp4`)
s3.initVideo(`${filePrefix}/VJ/Shinjuku_Night_2-1.mp4`)
s3.initVideo(`${filePrefix}/VJ/Shinjuku_Night_3-1.mp4`)
s3.initVideo(`${filePrefix}/VJ/shito.mp4`)
s3.initVideo(`${filePrefix}/VJ/storobo.mp4`)
s3.initVideo(`${filePrefix}/VJ/transmission.mp4`)
s3.initVideo(`${filePrefix}/VJ/_1080p_autumn_part_szkhaven_.mp4`)
s3.initVideo(`${filePrefix}/VJ/_1080p_Emotion_Sunset_szkhaven_.mp4`)
s3.initVideo(`${filePrefix}/VJ/_1080p_KAREHA01_szkhaven_.mp4`)

// FX
s2.initVideo(`${filePrefix}/VJ FX/01_noise1-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/01_noise1.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/02_noise2.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/03_circle.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/04_pillar.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/05-sub_line.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/05-sub_noise.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/05_switch.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/06_light.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/07_blink.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/08-sub_motion.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/08-sub_shape.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/08_trimotion.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/mono_building-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_circleshape-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_circle_1-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_circle_2-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_ColorPanel-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_cross_line-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_dot-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_dot_ring-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_line-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_LineCircle-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_line_motion-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_Spotlight-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/mono_Spotlight-1.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/mono_techbuilding-1.m4v`)
s2.initVideo(`${filePrefix}/VJ FX/storobo.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/white_1.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/white_2.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/white_3.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/white_4.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/white_5.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/white_6.mp4`)

// FX (Tolass)
s2.initVideo(`${filePrefix}/VJ FX/moving tolass.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/tolass dancing long.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/tolass dancing1.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/tolass dancing2.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/tolass dancing3.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/tolass dancing4.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/tolass dancing5.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/tolass waka.mp4`)
s2.initVideo(`${filePrefix}/VJ FX/tolass waving.mp4`)

// LOGOs
s1.initImage(`${filePrefix}/VJ LOGOs/tolassnite.png`)
